function Traj = LoadTraj(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [FLIGHTID,ARMTIME,LATITUDE,LONGITUDE,THRUST,ORIENTATION] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [FLIGHTID,ARMTIME,LATITUDE,LONGITUDE,THRUST,ORIENTATION] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [FlightID,armtime,Latitude,Longitude,Thrust,Orientation] =
%   importfile('trajectory.log',2, 4766);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/12/31 10:18:33

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Traj = struct('FlightID', dataArray{:, 1}, ...
 'armtime', dataArray{:, 2}, ...
 'Latitude', dataArray{:, 3}, ...
 'Longitude', dataArray{:, 4}, ...
 'Thrust', dataArray{:, 5}, ...
 'Orientation', dataArray{:, 6});

