ALTER TABLE Flight
  ADD COLUMN Battery_Capacity INT NOT NULL DEFAULT 23740 COMMENT 'W-hr';

ALTER TABLE Trajectory
  ADD COLUMN Battery_Energy INT NOT NULL DEFAULT 0 COMMENT 'W-hr',
  ADD COLUMN Max_Power BOOL NOT NULL DEFAULT false,
  ADD COLUMN Surplus_Energy DOUBLE NOT NULL DEFAULT 0;
